# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b74d25e7306e35065a0538239facd0e5ec19f8c4c2dc3be7d661f8b18fc944235afa74cd814e44bc69ecb75fd50c751d5530c2bac6c799ebda6f1e721f287a

test:
  secret_key_base: 67508cd7c9b8636c1651dc0d28d1f685c54282360273460830e71a202eeebe6df7967bca0a426ba62f04b7cb6553dc3f37432cfa396ad358f0519037ca6a07d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
